# Saving parameters ####

# Set the height and width of graphics (cm)
save_width <- 20
save_height <- 20


# Figure 2 ####
# An artificial modern sample bias scenario. The points in black show the true effects vector for noiseless synthetic data generated by a fast-biased survivorship curve. The points shown in colour are estimated effect vectors, estimated using GAM fixed effects standardization, with uncorrected estimates ($G_{ita}=T_tA_a$) shown in blue and corrected estimates ($G_{ita}=I_iT_tA_a$) shown in red.

set.seed(42)

# Create mock data
GSS_2 <- make_GSS(s=0.5, lambda=0.01, k=1, Beta=1)
scen_2 <- modern_TRA(nQ=100, nF=200, sdF=0.1, funcA=constBAI_trend, noiseSD=0.1, multiplicative=T, GSS=GSS_2, k=1)
tra_2 <- scen_2$tra
effects_2 <- scen_2$cv
names(effects_2) <- c("I", "T", "A")
names(effects_2$I) <- dimnames(tra_2)[[1]]


# Standardize
ta_2 <- standardize_tra(tra_2, model=list(I=FALSE, T=TRUE, A=TRUE), method="sfs")
ita_2 <- standardize_tra(tra_2, model=list(I=TRUE, T=TRUE, A=TRUE), method="sfs")

age_2 <- sapply(1:dim(tra_2)[1], grab_age, tra=tra_2, sparse=FALSE)


# Collate
df_true_2_I <-  data.frame(Method="True", effect="I", x=names(effects_2$I), y=effects_2$I, age=age_2)
df_ita_2_I <-  data.frame(Method="G=ITA", effect="I", x=names(ita_2$effects$I), y=ita_2$effects$I, age=age_2)


df_true_2_T <-  data.frame(Method="True", effect="T", x=names(effects_2$T), y=effects_2$T)
df_ta_2_T <-  data.frame(Method="G=TA", effect="T", x=names(ta_2$effects$T), y=ta_2$effects$T)
df_ita_2_T <-  data.frame(Method="G=ITA", effect="T", x=names(ita_2$effects$T), y=ita_2$effects$T)

df_true_2_A <-  data.frame(Method="True", effect="T", x=names(effects_2$A), y=effects_2$A)
df_ta_2_A <-  data.frame(Method="G=TA", effect="T", x=names(ta_2$effects$A), y=ta_2$effects$A)
df_ita_2_A <-  data.frame(Method="G=ITA", effect="T", x=names(ita_2$effects$A), y=ita_2$effects$A)

df_2_I <- rbind(
  df_true_2_I,
  df_ita_2_I
)

df_2_T <- rbind(
  df_true_2_T,
  df_ta_2_T,
  df_ita_2_T
)

df_2_T$x <- as.numeric(as.character(df_2_T$x))

df_2_A <- rbind(
  df_true_2_A,
  df_ta_2_A,
  df_ita_2_A
)

df_2_A$x <- as.numeric(as.character(df_2_A$x))


# Make graphs
fig_2_I <-  ggplot (df_2_I, aes(x=age, y=y, colour=Method)) + geom_point() + geom_smooth(fill=NA) + theme_bw() + xlab("Age of tree") + ylab("Individual effect") + scale_colour_manual(values=c("black", "red")) 

fig_2_T <- ggplot(df_2_T, aes(x=x, y=y, colour=Method)) + geom_line() + theme_bw() +  xlab("Time") + ylab("Time effect") + scale_colour_manual(values=c("black", "blue", "red")) 

fig_2_A <- ggplot(df_2_A, aes(x=x, y=y, colour=Method)) + geom_line() + theme_bw() + xlab("Age") + ylab("Age effect (mm)") + scale_colour_manual(values=c("black", "blue", "red"))

print(fig_2_I)
print(fig_2_T)
print(fig_2_A)

ggsave(filename="./Scenarios/fig_2_I.svg", plot=fig_2_I, width=15, height=6, units="cm")
ggsave(filename="./Scenarios/fig_2_T.svg", plot=fig_2_T,  width=15, height=6, units="cm")
ggsave(filename="./Scenarios/fig_2_A.svg", plot=fig_2_A,  width=15, height=6, units="cm")


# Figure 3 ####
# Comparing regional curve standardization and signal-free standardization with different data locations. 
# In all cases, the same time and age effect vectors were used to generate the data. 
# Left: a complete, balanced design. 
# The points in black show the true effects vectors, while the points in colour show the estimated effects vector, estimated via regional curve standardization (blue) and signal-free regional curve standardization (red).
# Center: a randomly unbalanced design, data points were retained entirely at random. 
# Right: a realistic unbalanced design, data points were retained according to a negative exponential survivorship simulation with uniform random birth years.}

set.seed(42)

# Effects
effects3 <- list()
effects3$I <- rep.int(1, 10)
names(effects3$I) <- paste("I", 1:10)

effects3$T <- rlnorm(50, sdlog=0.1)
names(effects3$T) <- paste("T", 1:50)

effects3$A <- constBAI_trend(1:50, k=1)
names(effects3$A) <- paste("A", 1:50)

effects3 <- rescale_effects(effects3, form="multiplicative")

# Balanced design
tra_3_a <-  effects3$I %o% effects3$T  %o% effects3$A  

rcs_3_a <- standardize_tra(tra_3_a, model=list(I=FALSE, A=TRUE, T=TRUE), method="rcs", sparse=FALSE)
sfs_3_a <- standardize_tra(tra_3_a, model=list(I=FALSE, A=TRUE, T=TRUE), method="sfs", sparse=FALSE)

# Realistic design
GSS_3 <- make_GSS(s=0, lambda=0.1, k=1)
str_3_c <- modern_TRA(nQ=10, nF=50, sdF=0, funcA=flat_trend, noiseSD=0, multiplicative=T, GSS=GSS_3)
tra_3_c <- tra_3_a
tra_3_c[is.na(str_3_c$tra)] <- NA

rcs_3_c <- standardize_tra(tra_3_c, model=list(I=FALSE, A=TRUE, T=TRUE), method="rcs", sparse=FALSE)
sfs_3_c <- standardize_tra(tra_3_c, model=list(I=FALSE, A=TRUE, T=TRUE), method="sfs", sparse=FALSE)

# Unbalanced design

# Remove same number of samples as in realistic case
tra_3_b <- tra_3_a
n_entries <- sum(!is.na(tra_3_c))
retained <- sample(1:length(tra_3_a), n_entries)
tra_3_b[] <- NA
tra_3_b[retained] <- tra_3_a[retained]

rcs_3_b <- standardize_tra(tra_3_b, model=list(I=FALSE, A=TRUE, T=TRUE), method="rcs", sparse=FALSE)
sfs_3_b <- standardize_tra(tra_3_b, model=list(I=FALSE, A=TRUE, T=TRUE), method="sfs", sparse=FALSE)

# Compile the effects

df_true_3_a_T <- data.frame(case="a", Method="True", effect="T", x=names(effects3$T), y=effects3$T)
df_true_3_a_A <- data.frame(case="a", Method="True", effect="A", x=names(effects3$A), y=effects3$A)
df_RCS_3_a_T <- data.frame(case="a", Method="RCS", effect="T", x=names(rcs_3_a$effects$T), y=rcs_3_a$effects$T)
df_RCS_3_a_A <- data.frame(case="a", Method="RCS", effect="A", x=names(rcs_3_a$effects$A), y=rcs_3_a$effects$A)
df_SFS_3_a_T <- data.frame(case="a", Method="SFS", effect="T", x=names(sfs_3_a$effects$T), y=sfs_3_a$effects$T)
df_SFS_3_a_A <- data.frame(case="a", Method="SFS", effect="A", x=names(sfs_3_a$effects$A), y=sfs_3_a$effects$A)

df_true_3_b_T <- data.frame(case="b", Method="True", effect="T", x=names(effects3$T), y=effects3$T)
df_true_3_b_A <- data.frame(case="b", Method="True", effect="A", x=names(effects3$A), y=effects3$A)
df_RCS_3_b_T <- data.frame(case="b", Method="RCS", effect="T", x=names(rcs_3_b$effects$T), y=rcs_3_b$effects$T)
df_RCS_3_b_A <- data.frame(case="b", Method="RCS", effect="A", x=names(rcs_3_b$effects$A), y=rcs_3_b$effects$A)
df_SFS_3_b_T <- data.frame(case="b", Method="SFS", effect="T", x=names(sfs_3_b$effects$T), y=sfs_3_b$effects$T)
df_SFS_3_b_A <- data.frame(case="b", Method="SFS", effect="A", x=names(sfs_3_b$effects$A), y=sfs_3_b$effects$A)

df_true_3_c_T <- data.frame(case="c", Method="True", effect="T", x=names(effects3$T), y=effects3$T)
df_true_3_c_A <- data.frame(case="c", Method="True", effect="A", x=names(effects3$A), y=effects3$A)
df_RCS_3_c_T <- data.frame(case="c", Method="RCS", effect="T", x=names(rcs_3_c$effects$T), y=rcs_3_c$effects$T)
df_RCS_3_c_A <- data.frame(case="c", Method="RCS", effect="A", x=names(rcs_3_c$effects$A), y=rcs_3_c$effects$A)
df_SFS_3_c_T <- data.frame(case="c", Method="SFS", effect="T", x=names(sfs_3_c$effects$T), y=sfs_3_c$effects$T)
df_SFS_3_c_A <- data.frame(case="c", Method="SFS", effect="A", x=names(sfs_3_c$effects$A), y=sfs_3_c$effects$A)


df_3 <- rbind(
  df_true_3_a_T,
  df_true_3_a_A,
  df_RCS_3_a_T,
  df_RCS_3_a_A,
  df_SFS_3_a_T,
  df_SFS_3_a_A,
  df_true_3_b_T,
  df_true_3_b_A,
  df_RCS_3_b_T,
  df_RCS_3_b_A,
  df_SFS_3_b_T,
  df_SFS_3_b_A,  
  df_true_3_c_T,
  df_true_3_c_A,
  df_RCS_3_c_T,
  df_RCS_3_c_A,
  df_SFS_3_c_T,
  df_SFS_3_c_A
)

df_3$x <- as.character(df_3$x)
df_3$x <- as.numeric(as.character(substr(df_3$x, 3, sapply(df_3$x, nchar))))

# Make the graph!

fig_3 <- ggplot(df_3, aes(y=y, x=x, colour=Method)) + geom_line() + facet_grid(effect~case, scales="free_y") + theme_bw() + ylab("Effect vectors") + xlab("Time (calendar year above, age below)") + scale_colour_manual(values=c("black", "blue", "red")) 

ggsave(filename="./Scenarios/fig_3.svg", plot=fig_3, width=save_width, height=save_height, units="cm")
ggsave(filename="./Scenarios/fig_3.pdf", plot=fig_3, width=save_width, height=save_height, units="cm")
